-- COMMIT 22 · CENTRO DE COMUNICACIONES
-- Ejecutar una sola vez en Supabase > SQL Editor.
create or replace function public.fc_is_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.admin_profiles where user_id=auth.uid() and coalesce(activo,true)=true);
$$;

create table if not exists public.communication_templates(
 id uuid primary key default gen_random_uuid(), nombre text not null, asunto text not null,
 cuerpo_html text not null default '', activa boolean not null default true,
 creado_por uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table if not exists public.communications(
 id uuid primary key default gen_random_uuid(), titulo text not null, asunto text not null, cuerpo_html text not null,
 canal text not null default 'email' check(canal in('email','interno','ambos')),
 segmento text not null default 'todos' check(segmento in('todos','activos','cuota_al_dia','adultos','jovenes','infantiles','seleccion')),
 destinatarios_ids uuid[] not null default '{}', estado text not null default 'borrador' check(estado in('borrador','programado','procesando','enviado','parcial','cancelado','error')),
 programado_para timestamptz, enviado_at timestamptz, total_destinatarios int not null default 0,
 enviados_ok int not null default 0, enviados_error int not null default 0, ultimo_error text,
 importante boolean not null default false, mostrar_desde timestamptz, mostrar_hasta timestamptz,
 creado_por uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table if not exists public.communication_recipients(
 id bigint generated by default as identity primary key, communication_id uuid not null references public.communications(id) on delete cascade,
 socio_id uuid references public.socios(id) on delete set null, email text, nombre text,
 estado text not null default 'pendiente' check(estado in('pendiente','enviado','error','omitido')),
 brevo_message_id text, error text, sent_at timestamptz, created_at timestamptz not null default now(),
 unique(communication_id,socio_id));

create table if not exists public.member_notices(
 id uuid primary key default gen_random_uuid(), communication_id uuid references public.communications(id) on delete cascade,
 socio_id uuid not null references public.socios(id) on delete cascade, titulo text not null, cuerpo_html text not null,
 importante boolean not null default false, leido_at timestamptz, created_at timestamptz not null default now(),
 unique(communication_id,socio_id));

alter table public.communication_templates enable row level security;
alter table public.communications enable row level security;
alter table public.communication_recipients enable row level security;
alter table public.member_notices enable row level security;

drop policy if exists c22_templates_admin on public.communication_templates;
create policy c22_templates_admin on public.communication_templates for all using(public.fc_is_admin()) with check(public.fc_is_admin());
drop policy if exists c22_comms_admin on public.communications;
create policy c22_comms_admin on public.communications for all using(public.fc_is_admin()) with check(public.fc_is_admin());
drop policy if exists c22_recipients_admin on public.communication_recipients;
create policy c22_recipients_admin on public.communication_recipients for all using(public.fc_is_admin()) with check(public.fc_is_admin());
drop policy if exists c22_notices_admin on public.member_notices;
create policy c22_notices_admin on public.member_notices for all using(public.fc_is_admin()) with check(public.fc_is_admin());
drop policy if exists c22_notices_member_read on public.member_notices;
create policy c22_notices_member_read on public.member_notices for select using(exists(select 1 from public.socios s where s.id=member_notices.socio_id and s.auth_user_id=auth.uid()));
drop policy if exists c22_notices_member_update on public.member_notices;
create policy c22_notices_member_update on public.member_notices for update using(exists(select 1 from public.socios s where s.id=member_notices.socio_id and s.auth_user_id=auth.uid())) with check(exists(select 1 from public.socios s where s.id=member_notices.socio_id and s.auth_user_id=auth.uid()));

create or replace function public.c22_prepare_recipients(p_communication_id uuid) returns integer language plpgsql security definer set search_path=public as $$
declare c public.communications; n int;
begin
 if not public.fc_is_admin() then raise exception 'Acceso denegado'; end if;
 select * into c from public.communications where id=p_communication_id;
 if not found then raise exception 'Comunicación no encontrada'; end if;
 delete from public.communication_recipients where communication_id=c.id;
 insert into public.communication_recipients(communication_id,socio_id,email,nombre)
 select c.id,s.id,s.email,trim(concat_ws(' ',s.nombre,s.apellidos)) from public.socios s
 where nullif(trim(coalesce(s.email,'')),'') is not null and (
 c.segmento='todos' or (c.segmento='activos' and coalesce(s.estado::text,'activo')='activo') or
 (c.segmento='cuota_al_dia' and coalesce(s.cuota_al_dia,false)) or
 (c.segmento='adultos' and lower(coalesce(s.categoria::text,'')) like '%adult%') or
 (c.segmento='jovenes' and lower(coalesce(s.categoria::text,'')) like '%jov%') or
 (c.segmento='infantiles' and lower(coalesce(s.categoria::text,'')) like '%inf%') or
 (c.segmento='seleccion' and s.id=any(c.destinatarios_ids)));
 get diagnostics n=row_count;
 update public.communications set total_destinatarios=n,updated_at=now() where id=c.id;
 if c.canal in('interno','ambos') then
  insert into public.member_notices(communication_id,socio_id,titulo,cuerpo_html,importante)
  select c.id,r.socio_id,c.titulo,c.cuerpo_html,c.importante from public.communication_recipients r where r.communication_id=c.id and r.socio_id is not null
  on conflict(communication_id,socio_id) do update set titulo=excluded.titulo,cuerpo_html=excluded.cuerpo_html,importante=excluded.importante;
 end if;
 return n;
end $$;

grant execute on function public.c22_prepare_recipients(uuid) to authenticated;

create or replace view public.c22_communication_summary with(security_invoker=true) as
select c.*,count(r.id) filter(where r.estado='pendiente') pendientes,count(r.id) filter(where r.estado='enviado') enviados,count(r.id) filter(where r.estado='error') errores
from public.communications c left join public.communication_recipients r on r.communication_id=c.id group by c.id;

insert into public.communication_templates(nombre,asunto,cuerpo_html)
select * from (values
 ('Aviso de entradas','Entradas disponibles · Frente Comepipas','<h2>Entradas disponibles</h2><p>Ya está abierto el plazo de solicitudes en el Área del Socio.</p>'),
 ('Desplazamiento','Nuevo desplazamiento · Frente Comepipas','<h2>Nuevo desplazamiento</h2><p>Consulta las condiciones y realiza tu solicitud desde el Área del Socio.</p>'),
 ('Convocatoria','Convocatoria de la Peña','<h2>Convocatoria</h2><p>Estimado/a socio/a:</p><p>Te informamos de la próxima convocatoria.</p>')
) v(nombre,asunto,cuerpo_html) where not exists(select 1 from public.communication_templates);
